Feature/add edit event user endpoint
LT-Students/DigitalOffice-EventService pull request #10
Opened 2023-03-23 15:13 UTC by liza459

https://trello.com/c/8bGTGxEN/220-eventservice-add-eventuser-edit-endpoint

https://docs.google.com/document/d/1upUYu5MaGjBW2MKP-wHM2hwef8t6TPGzpVNkF8njJDI/edit#heading=h.7jjwan5qecem

Also
- rights check fix in CreateEventUserCommand;
- fix EventUserInfoMapper;

2023-03-24 09:04 UTC, SolovyovDmitry requested changes
I'd suggest running code cleanup. Default profile made 20 files change with missing spaces, unused usings etc. Remove updates from .csproj and insert the block we always use. The logic itself looks OK, but I will check harder a bit later

2023-03-24 09:04 UTC, SolovyovDmitry commented on Common.Configurations.targets
Why did you change spacing? And we have those spaces in the end everywhere

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Broker/EventService.Broker.csproj
It shouldn't be here

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Business/Commands/EventUser/CreateEventUserCommand.cs
> +      (dbEvent.Access == AccessType.Opened &&
format it to be at the same level

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Business/Commands/EventUser/EditEventUserCommand.cs
> +        validationResult.Errors.Select(vf => vf.ErrorMessage).ToList());
Select().ToList() => ConvertAll()

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Business/Commands/EventUser/EditEventUserCommand.cs
> +    if (!await _accessValidator.HasRightsAsync(Rights.AddEditRemoveUsers) &&
format

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Business/Commands/EventUser/EditEventUserCommand.cs
> +    OperationResultResponse<bool> response = new();
Initialization can be simplified

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Business/EventService.Business.csproj
Shouldn't be here

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Data.Provider.MsSql.Ef/EventService.Data.Provider.MsSql.Ef.csproj
same

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Data.Provider/EventService.Data.Provider.csproj
same

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Data/EventService.Data.csproj
same

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Data/EventUserRepository.cs
> +    return _provider.EventsUsers.AsNoTracking().FirstOrDefaultAsync(eu =>eu.Id == eventUserId);
missing space before eu.Id

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService.Validation/EventUser/EditEventUserRequestValidator.cs
> +    ValidationContext<(Guid,JsonPatchDocument<EditEventUserRequest>)> context)
missing space

2023-03-24 09:04 UTC, SolovyovDmitry commented on src/EventService/Controllers/EventUserController.cs
> +    return await command.ExecuteAsync(eventUserId,request);
missing space

2023-03-24 12:13 UTC, liza459 commented on Common.Configurations.targets
![изображение](https://user-images.githubusercontent.com/108836868/227517663-25742e90-902e-424b-9127-061116e378aa.png)

There are no spaces at the beginning of the line, this is a git bug.

2023-03-24 14:19 UTC, Draktolli commented on src/EventService.Validation/EventUser/EditEventUserRequestValidator.cs
> +            "Uncorrect user status"
In my Opinion it's better to use 
`Enum.TryParse(x.value?.ToString(), out EventUserStatus status) ?
status == EventUserStatus.Participant &&`
and etc

2023-03-24 14:20 UTC, Draktolli commented on src/EventService.Validation/EventUser/EditEventUserRequestValidator.cs
> +            "Uncorrect user status"
In other projects messages was writen in .resx file

2023-03-27 11:56 UTC, TIove commented on Common.Configurations.targets
That's not a bug, there were **'spaces'** and became **'tabs'**. In VS tabs look like spaces, but it doesn't. 

@SolovyovDmitry What do u mean about **'those spaces in the end'**? Does Liza have to delete them or not?

2023-03-27 13:40 UTC, TIove commented on src/EventService.Business/Commands/EventUser/CreateEventUserCommand.cs
> +    bool userWithRight = await _accessValidator.HasRightsAsync(senderId, Rights.AddEditRemoveUsers);
userHasRight is prettier, fmpov

2023-03-27 13:40 UTC, TIove commented on src/EventService.Business/Commands/EventUser/EditEventUserCommand.cs
> +  public async Task<OperationResultResponse<bool>> ExecuteAsync(Guid eventUserId, JsonPatchDocument<EditEventUserRequest> patch)
Space after ctor. And separate params to few lines.

2023-03-27 13:40 UTC, TIove commented on src/EventService.Models.Dto/Requests/EventUser/EditEventUserRequest.cs
> +namespace LT.DigitalOffice.EventService.Models.Dto.Requests.EventUser
namespace without brackets

2023-03-27 13:40 UTC, TIove commented on src/EventService.Validation/EventUser/EditEventUserRequestValidator.cs
> +            "Uncorrect user status"
Incorrect*

2023-03-27 13:40 UTC, TIove commented on src/EventService.Validation/EventUser/EditEventUserRequestValidator.cs
> +            "Uncorrect notify"
Incorrect*

2023-03-29 08:49 UTC, SolovyovDmitry commented on Common.Configurations.targets
@TIove I mean these
![image](https://user-images.githubusercontent.com/101804724/228479788-a3ede009-04a5-4f2d-8b28-da6c396c70b0.png)

2023-03-29 08:49 UTC, SolovyovDmitry commented on Common.Configurations.targets
in the end of the lines

2023-04-11 10:30 UTC, SolovyovDmitry approved these changes

2023-04-11 10:30 UTC, SolovyovDmitry commented on src/EventService.Data/EventUserRepository.cs
>      if (filter.Status is not null)
can it be !HasValue?

2023-04-11 10:30 UTC, SolovyovDmitry commented on src/EventService.Mappers/Models/EventUserInfoMapper.cs
> +      Status = eu.Status.ToString(),
Why did you decide to change?

2023-04-11 11:10 UTC, SolovyovDmitry approved these changes

2023-04-11 12:46 UTC, liza459 commented on src/EventService.Mappers/Models/EventUserInfoMapper.cs
> +      Status = eu.Status.ToString(),
I tried to fix the fact that the enum is returned as a number. It was a bad decision.

Now added an attribute ( `[JsonConverter(typeof(StringEnumConverter))]`) to the model.

2023-04-14 14:14 UTC, VLiamin approved these changes

2023-04-14 14:14 UTC, VLiamin commented on src/EventService.Validation/EventUser/EditEventUserRequestValidator.cs
> +                (((status == EventUserStatus.Refused || status == EventUserStatus.Invited) && isUser)||
May be add space before |

2023-04-15 08:48 UTC, TIove approved these changes

2023-04-15 12:51 UTC, TheDioBrando approved these changes

2023-04-17 12:06 UTC, Segway-svg approved these changes

2023-04-17 12:08 UTC, merged